// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Setup.Infrastructure;

#nullable disable

namespace Setup.Infrastructure.Migrations
{
    [DbContext(typeof(SetupContext))]
    [Migration("20251112163109_InitialFixedRelations")]
    partial class InitialFixedRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Setup.Infrastructure.Models.ComputerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RAM")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Storage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("Setup.Infrastructure.Models.HardwareModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hardware");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Setup.Infrastructure.Models.PeripheryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("Peripheries");
                });

            modelBuilder.Entity("Setup.Infrastructure.Models.SoftwareModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Antivirus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OSVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId")
                        .IsUnique();

                    b.ToTable("Softwares");
                });

            modelBuilder.Entity("Setup.Infrastructure.Models.CPUModel", b =>
                {
                    b.HasBaseType("Setup.Infrastructure.Models.HardwareModel");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cores")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Frequency")
                        .HasColumnType("REAL");

                    b.Property<int>("Threads")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ComputerId")
                        .IsUnique();

                    b.ToTable("CPUs");
                });

            modelBuilder.Entity("Setup.Infrastructure.Models.GPUModel", b =>
                {
                    b.HasBaseType("Setup.Infrastructure.Models.HardwareModel");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("TEXT");

                    b.Property<double>("CoreClock")
                        .HasColumnType("REAL");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("VRAM")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ComputerId")
                        .IsUnique();

                    b.ToTable("GPUs");
                });

            modelBuilder.Entity("Setup.Infrastructure.Models.PeripheryModel", b =>
                {
                    b.HasOne("Setup.Infrastructure.Models.ComputerModel", "Computer")
                        .WithMany("Peripheries")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("Setup.Infrastructure.Models.SoftwareModel", b =>
                {
                    b.HasOne("Setup.Infrastructure.Models.ComputerModel", "Computer")
                        .WithOne("Software")
                        .HasForeignKey("Setup.Infrastructure.Models.SoftwareModel", "ComputerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("Setup.Infrastructure.Models.CPUModel", b =>
                {
                    b.HasOne("Setup.Infrastructure.Models.ComputerModel", "Computer")
                        .WithOne("CPU")
                        .HasForeignKey("Setup.Infrastructure.Models.CPUModel", "ComputerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Setup.Infrastructure.Models.HardwareModel", null)
                        .WithOne()
                        .HasForeignKey("Setup.Infrastructure.Models.CPUModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("Setup.Infrastructure.Models.GPUModel", b =>
                {
                    b.HasOne("Setup.Infrastructure.Models.ComputerModel", "Computer")
                        .WithOne("GPU")
                        .HasForeignKey("Setup.Infrastructure.Models.GPUModel", "ComputerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Setup.Infrastructure.Models.HardwareModel", null)
                        .WithOne()
                        .HasForeignKey("Setup.Infrastructure.Models.GPUModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("Setup.Infrastructure.Models.ComputerModel", b =>
                {
                    b.Navigation("CPU");

                    b.Navigation("GPU");

                    b.Navigation("Peripheries");

                    b.Navigation("Software");
                });
#pragma warning restore 612, 618
        }
    }
}
